name: development zybte-sso-verify

on:
  push:
    branches:
      - 'CI'
  pull_request:
    branches:
      - 'CI'

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
          scope: '@zbyteio'
      - name: Clean Install NPM modules
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.FORCI}}
      - name: Verify code format
        run: npm run check-fmt
      - name: Check code lint
        continue-on-error: true
        run: npm run lint
      - name: Build zbyte-sso-verify lib
        run: npm run build

  node_module_publish:
    needs: code-quality-check
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
          scope: '@zbyteio'
      - name: Version
        run: |
          commit=$(git rev-parse HEAD | head -c 7)
          jq ".version = \"0.0.0-$commit\"" package.json > /tmp/file && mv /tmp/file package.json 
      - name: Clean Install NPM modules
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build zbyte-sso-verify lib
        run: npm run build
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}