name: zybte-sso-verify package

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Clean Install NPM modules
        run: npm ci
      - name: Execute Tests
        run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com
      - name: Clean Install NPM modules
        run: npm ci
      - name: Build zbyte sso verify 
        run: npm run build
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.FORCI}}